var annotated_dup =
[
    [ "AdministrationHistoriqueCommande", "class_administration_historique_commande.html", "class_administration_historique_commande" ],
    [ "AdministrationPaiementLivraison", "class_administration_paiement_livraison.html", "class_administration_paiement_livraison" ],
    [ "AdministrationProduit", "class_administration_produit.html", "class_administration_produit" ],
    [ "AdministrationUser", "class_administration_user.html", "class_administration_user" ],
    [ "ChiffreAffaire", "class_chiffre_affaire.html", "class_chiffre_affaire" ],
    [ "Controleur", "interface_controleur.html", "interface_controleur" ],
    [ "ControleurAccueil", "class_controleur_accueil.html", "class_controleur_accueil" ],
    [ "ControleurAdministrationHistoriqueCommande", "class_controleur_administration_historique_commande.html", "class_controleur_administration_historique_commande" ],
    [ "ControleurAdministrationPaiementLivraison", "class_controleur_administration_paiement_livraison.html", "class_controleur_administration_paiement_livraison" ],
    [ "ControleurAdministrationProduit", "class_controleur_administration_produit.html", "class_controleur_administration_produit" ],
    [ "ControleurAdministrationUser", "class_controleur_administration_user.html", "class_controleur_administration_user" ],
    [ "ControleurChiffreAffaire", "class_controleur_chiffre_affaire.html", "class_controleur_chiffre_affaire" ],
    [ "ControleurErreur", "class_controleur_erreur.html", "class_controleur_erreur" ],
    [ "ControleurFAQ", "class_controleur_f_a_q.html", "class_controleur_f_a_q" ],
    [ "ControleurInscription", "class_controleur_inscription.html", "class_controleur_inscription" ],
    [ "ControleurLogin", "class_controleur_login.html", "class_controleur_login" ],
    [ "ControleurProductCategorie", "class_controleur_product_categorie.html", "class_controleur_product_categorie" ],
    [ "ControleurProduitList", "class_controleur_produit_list.html", "class_controleur_produit_list" ],
    [ "ControleurRecherche", "class_controleur_recherche.html", "class_controleur_recherche" ],
    [ "ControleurTunnel", "class_controleur_tunnel.html", "class_controleur_tunnel" ],
    [ "ControleurUserProfile", "class_controleur_user_profile.html", "class_controleur_user_profile" ],
    [ "Modele", "class_modele.html", "class_modele" ],
    [ "ModeleFAQ", "class_modele_f_a_q.html", "class_modele_f_a_q" ],
    [ "Produit", "class_produit.html", "class_produit" ],
    [ "Recherche", "class_recherche.html", "class_recherche" ],
    [ "Register", "class_register.html", "class_register" ],
    [ "Routeur", "class_routeur.html", "class_routeur" ],
    [ "UserLogin", "class_user_login.html", "class_user_login" ],
    [ "UserProfile", "class_user_profile.html", "class_user_profile" ],
    [ "Vue", "class_vue.html", "class_vue" ]
];